language: generic 
sudo: required
services: 
  - docker

before_install: 
  - docker build -f docker.dev -t filimemagalhaes/docker-react .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
